# Generated by Django 6.0.5 on 2026-05-22 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('transport_type', models.CharField(choices=[('truck', 'Camión'), ('van', 'Furgoneta'), ('motorcycle', 'Motocicleta'), ('bicycle', 'Bicicleta')], max_length=20)),
                ('capacity_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transports', to='drivers.driver')),
            ],
            options={
                'db_table': 'transports',
                'ordering': ['name'],
            },
        ),
    ]
