# Generated by Django 6.0.5 on 2026-05-27 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('TRUCK', 'Truck'), ('VAN', 'Van'), ('MOTORCYCLE', 'Motorcycle'), ('BIKE', 'Bike')], max_length=20)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.SmallIntegerField()),
                ('capacity_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('capacity_m3', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_ROUTE', 'In Route'), ('MAINTENANCE', 'Maintenance'), ('INACTIVE', 'Inactive')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'transport',
                'verbose_name_plural': 'transports',
                'ordering': ['license_plate'],
            },
        ),
    ]
